# Dados do Brasileirão: Previsões e probabilidade

# Pré-Processamentos

In [1]:
#Bibliotecas
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings as wa

%matplotlib inline
 
### ignorando warnings do tipo FutureWarning
wa.simplefilter( action='ignore', category= FutureWarning)
pd.options.mode.chained_assignment = None

In [2]:
#Dados dos jogos do brasileirão de 2003 a 2021
path_periodo = "https://github.com/juvenalfonseca/python/blob/master/datasets/campeonato-brasileiro-pontos-corridos-2003-2020-periodo.csv?raw=true"
path_jogos = "https://github.com/juvenalfonseca/python/blob/master/datasets/campeonato-brasileiro-pontos-corridos-2003-2020-jogos.csv?raw=true"
 
df_periodo = pd.read_csv(path_periodo, delimiter=";")
df_jogos   = pd.read_csv(path_jogos  , delimiter=";")

In [3]:
#deixando os nomes das colunas em minusculo
df_periodo.columns = df_periodo.columns.str.lower()
df_jogos.columns   = df_jogos.columns.str.lower()

In [4]:
### altera campos de datas de character para date
df_periodo['inicio' ] = pd.to_datetime(df_periodo['inicio'], format="%d/%m/%Y")
df_periodo['fim'    ] = pd.to_datetime(df_periodo['fim'   ], format="%d/%m/%Y")
df_jogos['data'     ] = pd.to_datetime(df_jogos['data'    ], format="%d/%m/%Y")

In [5]:
df_jogos

,rodada,data,horário,dia,mandante,visitante,vencedor,arena,mandante placar,visitante placar,estado mandante,estado visitante,estado vencedor
0,1,2003-03-29,16h00,Sábado,Athlético-PR,Grêmio,Athlético-PR,Arena da Baixada,2,0,PR,RS,PR
1,1,2003-03-29,16h00,Sábado,Guarani,Vasco,Guarani,Brinco de Ouro,4,2,SP,RJ,SP
2,1,2003-03-30,16h00,Domingo,Fortaleza,Bahia,-,Castelão,0,0,CE,BA,-
3,1,2003-03-30,16h00,Domingo,Flamengo,Coritiba,-,Maracanã,1,1,RJ,PR,-
4,1,2003-03-30,16h00,Domingo,Vitória,Figueirense,-,Barradão,1,1,ES,SC,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7261,38,2021-02-25,21:30,Quinta-Feira,Internacional,Corinthians,-,Beira Rio,0,0,RS,SP,-
7262,38,2021-02-25,21:30,Quinta-Feira,Bahia,Santos,Bahia,Itaipava Arena Fonte Nova,2,0,BA,SP,BA
7263,38,2021-02-25,21:30,Quinta-Feira,Athlético-PR,Sport,Athlético-PR,Arena da Baixada,2,0,PR,PE,PR
7264,38,2021-02-25,21:30,Quinta-Feira,Ceará,Botafogo-RJ,Ceará,Castelão,2,1,CE,RJ,CE
7265,38,2021-02-25,21:30,Quinta-Feira,Atlético-GO,Coritiba,Atlético-GO,Antônio Accioly,3,1,GO,PR,GO

In [6]:
### captalizar strings
df_jogos['dia'      ] = df_jogos['dia'      ].str.title()
df_jogos['mandante' ] = df_jogos['mandante' ].str.title()
df_jogos['visitante'] = df_jogos['visitante'].str.title()
df_jogos['vencedor' ] = df_jogos['vencedor' ].str.title()
df_jogos['arena'    ] = df_jogos['arena'    ].apply(lambda x: x.title())

df_jogos.head()

,rodada,data,horário,dia,mandante,visitante,vencedor,arena,mandante placar,visitante placar,estado mandante,estado visitante,estado vencedor
0,1,2003-03-29,16h00,Sábado,Athlético-Pr,Grêmio,Athlético-Pr,Arena Da Baixada,2,0,PR,RS,PR
1,1,2003-03-29,16h00,Sábado,Guarani,Vasco,Guarani,Brinco De Ouro,4,2,SP,RJ,SP
2,1,2003-03-30,16h00,Domingo,Fortaleza,Bahia,-,Castelão,0,0,CE,BA,-
3,1,2003-03-30,16h00,Domingo,Flamengo,Coritiba,-,Maracanã,1,1,RJ,PR,-
4,1,2003-03-30,16h00,Domingo,Vitória,Figueirense,-,Barradão,1,1,ES,SC,-

In [7]:
### junta os datasets e retorna apenas os registros corretos criados na junção
df_periodo['key'] = 1
df_jogos['key'] = 1
 
df = pd.merge(df_periodo, df_jogos, on ='key').drop("key", 1)
df = df.query('data >= inicio & data <= fim')

df

,torneio,inicio,fim,rodada,data,horário,dia,mandante,visitante,vencedor,arena,mandante placar,visitante placar,estado mandante,estado visitante,estado vencedor
0,BRA2003,2003-03-29,2003-12-14,1,2003-03-29,16h00,Sábado,Athlético-Pr,Grêmio,Athlético-Pr,Arena Da Baixada,2,0,PR,RS,PR
1,BRA2003,2003-03-29,2003-12-14,1,2003-03-29,16h00,Sábado,Guarani,Vasco,Guarani,Brinco De Ouro,4,2,SP,RJ,SP
2,BRA2003,2003-03-29,2003-12-14,1,2003-03-30,16h00,Domingo,Fortaleza,Bahia,-,Castelão,0,0,CE,BA,-
3,BRA2003,2003-03-29,2003-12-14,1,2003-03-30,16h00,Domingo,Flamengo,Coritiba,-,Maracanã,1,1,RJ,PR,-
4,BRA2003,2003-03-29,2003-12-14,1,2003-03-30,16h00,Domingo,Vitória,Figueirense,-,Barradão,1,1,ES,SC,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130783,BRA2020,2020-08-08,2021-02-25,38,2021-02-25,21:30,Quinta-Feira,Internacional,Corinthians,-,Beira Rio,0,0,RS,SP,-
130784,BRA2020,2020-08-08,2021-02-25,38,2021-02-25,21:30,Quinta-Feira,Bahia,Santos,Bahia,Itaipava Arena Fonte Nova,2,0,BA,SP,BA
130785,BRA2020,2020-08-08,2021-02-25,38,2021-02-25,21:30,Quinta-Feira,Athlético-Pr,Sport,Athlético-Pr,Arena Da Baixada,2,0,PR,PE,PR
130786,BRA2020,2020-08-08,2021-02-25,38,2021-02-25,21:30,Quinta-Feira,Ceará,Botafogo-Rj,Ceará,Castelão,2,1,CE,RJ,CE
130787,BRA2020,2020-08-08,2021-02-25,38,2021-02-25,21:30,Quinta-Feira,Atlético-Go,Coritiba,Atlético-Go,Antônio Accioly,3,1,GO,PR,GO

In [8]:
### top 10 clubes gols marcados
gols_mandante_time  = df.groupby('mandante' )['mandante placar' ].sum().sort_values(ascending=False).reset_index()
gols_mandante_time.rename(columns  = {"mandante" : "time", 'mandante placar' : 'gols marcados' }, inplace=True)
 
gols_visitante_time = df.groupby('visitante')['visitante placar'].sum().sort_values(ascending=False).reset_index()
gols_visitante_time.rename(columns = {"visitante": "time", 'visitante placar': 'gols marcados' }, inplace=True)
 
gols_time = pd.concat([gols_mandante_time, gols_visitante_time])
 
gols_marcados_time = gols_time.groupby('time')['gols marcados'].sum().sort_values(ascending=False).reset_index()
gols_marcados_time.head(10)

            time  gols marcados
0         Santos           1060
1      São Paulo           1037
2       Flamengo            984
3       Cruzeiro            978
4    Atlético-Mg            967
5     Fluminense            946
6         Grêmio            912
7  Internacional            893
8   Athlético-Pr            892
9      Palmeiras            889

# Funções matematicas utilizadas

In [9]:
# importando numero euler(e)
from math import e
print(e)

2.718281828459045

In [10]:
#Fatorial de um numero
def fatorial(numero):
    resultado=1
    count=1

    while count <= numero:
        resultado *= count
        count += 1
        
    return resultado

#Probabilidade Poisson
def dist_poisson(media, x):
    resultado = (media**x)*(e**(-media))/fatorial(x)
    return resultado

# Probabilidade de gols

calculos baseados no video: https://www.youtube.com/watch?v=yDy5fPT_oIc&t=301s

In [11]:
#Seleção de quais jogos se basear
sel = ['BRA2019']
selecao = df['torneio'].isin(sel)
test = df[selecao]

## -Times como Mandante

## Distribuição de Probabilidade

In [12]:
#agrupamento
a = test.groupby(['mandante', 'mandante placar'])['mandante placar'].count().unstack()

#tratando dados faltantes (vai ser util para um monte de coisa)
n = test['mandante placar'].unique()

for i in n:
    a[i].fillna(0, inplace = True)
    
#criando coluna com o total para tirar as metricas
a['total'] = 0

for i in n:
    a['total'] += a[i]
    
#criando coluna com a media de gols
a['soma ponderada'] = 0

for i in n:
    a['soma ponderada'] += a[i]*i

a['media de gols'] = a['soma ponderada']/a['total']

b = a.copy()

#transformando em probabilidade - distribuição de probabilidade
for i in n:
    a[i] = a[i]/a['total']
    
#tirando as colunas que não mais preciso
a.drop(['total', 'soma ponderada'], 1, inplace=True)
a

#deixando em porcentagem para melhor visualização
a_per = a.copy()

for i in n:
    a_per[i] = a_per[i].apply(lambda x: x*100)
    
a_per

mandante placar,0,1,2,3,4,5,6,media de gols
mandante,,,,,,,,
Athlético-Pr,26.315789,47.368421,5.263158,5.263158,15.789474,0.000000,0.000000,1.368421
Atlético-Mg,21.052632,21.052632,52.631579,0.000000,5.263158,0.000000,0.000000,1.473684
Avaí,52.631579,42.105263,5.263158,0.000000,0.000000,0.000000,0.000000,0.526316
Bahia,15.789474,57.894737,10.526316,15.789474,0.000000,0.000000,0.000000,1.263158
Botafogo-Rj,42.105263,26.315789,21.052632,10.526316,0.000000,0.000000,0.000000,1.000000
Ceará,36.842105,26.315789,26.315789,0.000000,10.526316,0.000000,0.000000,1.210526
Chapecoense,36.842105,47.368421,10.526316,5.263158,0.000000,0.000000,0.000000,0.842105
Corinthians,15.789474,47.368421,26.315789,10.526316,0.000000,0.000000,0.000000,1.315789
Cruzeiro,42.105263,47.368421,10.526316,0.000000,0.000000,0.000000,0.000000,0.684211
Csa,36.842105,42.105263,15.789474,5.263158,0.000000,0.000000,0.000000,0.894737
Flamengo,5.263158,10.526316,15.789474,42.105263,15.789474,0.000000,10.526316,2.947368
Fluminense,36.842105,42.105263,15.789474,0.000000,5.263158,0.000000,0.000000,0.947368
Fortaleza,21.052632,26.315789,47.368421,5.263158,0.000000,0.000000,0.000000,1.368421
Goiás,15.789474,31.578947,31.578947,15.789474,5.263158,0.000000,0.000000,1.631579
Grêmio,15.789474,21.052632,31.578947,21.052632,5.263158,0.000000,5.263158,2.000000
Internacional,15.789474,36.842105,31.578947,15.789474,0.000000,0.000000,0.000000,1.473684
Palmeiras,0.000000,57.894737,10.526316,10.526316,10.526316,5.263158,5.263158,2.105263
Santos,10.526316,21.052632,26.315789,21.052632,15.789474,0.000000,5.263158,2.315789
São Paulo,26.315789,42.105263,21.052632,5.263158,5.263158,0.000000,0.000000,1.210526
Vasco,15.789474,63.157895,21.052632,0.000000,0.000000,0.000000,0.000000,1.052632

## Distribuição Poisson

In [13]:
#aplicando formula em cada valor
for i in n:
    b[i] = dist_poisson(b['media de gols'], i)

#tirando as colunas que não mais preciso
b.drop(['total', 'soma ponderada'], 1, inplace=True)

#deixando em porcentagem para melhor visualização
b_per = b.copy()

for i in n:
    b_per[i] = b_per[i].apply(lambda x: x*100)
    
b_per

mandante placar,0,1,2,3,4,5,6,media de gols
mandante,,,,,,,,
Athlético-Pr,25.450850,34.827479,23.829328,10.869518,3.718519,1.017700,0.232107,1.368421
Atlético-Mg,22.907995,33.759150,24.875164,12.219379,4.501876,1.326869,0.325898,1.473684
Avaí,59.077751,31.093553,8.182514,1.435529,0.188885,0.019883,0.001744,0.526316
Bahia,28.275969,35.717013,22.558114,9.498153,2.999417,0.757747,0.159526,1.263158
Botafogo-Rj,36.787944,36.787944,18.393972,6.131324,1.532831,0.306566,0.051094,1.000000
Ceará,29.804037,36.078572,21.837030,8.811433,2.666618,0.645602,0.130253,1.210526
Chapecoense,43.080262,36.278115,15.274996,4.287718,0.902677,0.152030,0.021338,0.842105
Corinthians,26.826245,35.297691,23.222165,10.185160,3.350382,0.881679,0.193351,1.315789
Cruzeiro,50.448835,34.517624,11.808661,2.693203,0.460680,0.063040,0.007189,0.684211
Csa,40.871514,36.569249,16.359927,4.879277,1.091417,0.195306,0.029125,0.894737
Flamengo,5.247762,15.467089,22.793605,22.393717,16.500634,9.726689,4.778023,2.947368
Fluminense,38.776010,36.735168,17.400869,5.495011,1.301450,0.246591,0.038935,0.947368
Fortaleza,25.450850,34.827479,23.829328,10.869518,3.718519,1.017700,0.232107,1.368421
Goiás,19.562046,31.917022,26.037570,14.160784,5.776109,1.884836,0.512543,1.631579
Grêmio,13.533528,27.067057,27.067057,18.044704,9.022352,3.608941,1.202980,2.000000
Internacional,22.907995,33.759150,24.875164,12.219379,4.501876,1.326869,0.325898,1.473684
Palmeiras,12.181361,25.644971,26.994707,18.943654,9.970344,4.198040,1.472996,2.105263
Santos,9.868824,22.854119,26.462664,20.427320,11.826343,5.477464,2.114109,2.315789
São Paulo,29.804037,36.078572,21.837030,8.811433,2.666618,0.645602,0.130253,1.210526
Vasco,34.901807,36.738744,19.336181,6.784625,1.785428,0.375880,0.065944,1.052632

## -Time como Visitante

## Distribuição de Probabilidade

In [14]:
#agrupamento
c = test.groupby(['visitante', 'visitante placar'])['visitante placar'].count().unstack()

#tratando dados faltantes (vai ser util para um monte de coisa)
n = test['visitante placar'].unique()

for i in n:
    c[i].fillna(0, inplace = True)
    
#criando coluna com o total para tirar as metricas
c['total'] = 0

for i in n:
    c['total'] += c[i]
    
#criando coluna com a media de gols
c['soma ponderada'] = 0

for i in n:
    c['soma ponderada'] += c[i]*i

c['media de gols'] = c['soma ponderada']/c['total']

d = c.copy()

#transformando em probabilidade - distribuição de probabilidade
for i in n:
    c[i] = c[i]/c['total']
    
#tirando as colunas que não mais preciso
c.drop(['total', 'soma ponderada'], 1, inplace=True)

#deixando em porcentagem para melhor visualização
c_per = c.copy()

for i in n:
    c_per[i] = c_per[i].apply(lambda x: x*100)
    
c_per

visitante placar,0,1,2,3,4,5,media de gols
visitante,,,,,,,
Athlético-Pr,10.526316,57.894737,26.315789,0.000000,5.263158,0.000000,1.315789
Atlético-Mg,36.842105,36.842105,26.315789,0.000000,0.000000,0.000000,0.894737
Avaí,57.894737,42.105263,0.000000,0.000000,0.000000,0.000000,0.421053
Bahia,31.578947,36.842105,26.315789,5.263158,0.000000,0.000000,1.052632
Botafogo-Rj,57.894737,21.052632,21.052632,0.000000,0.000000,0.000000,0.631579
Ceará,47.368421,36.842105,15.789474,0.000000,0.000000,0.000000,0.684211
Chapecoense,42.105263,42.105263,10.526316,5.263158,0.000000,0.000000,0.789474
Corinthians,36.842105,42.105263,15.789474,5.263158,0.000000,0.000000,0.894737
Cruzeiro,42.105263,42.105263,15.789474,0.000000,0.000000,0.000000,0.736842
Csa,68.421053,26.315789,5.263158,0.000000,0.000000,0.000000,0.368421
Flamengo,15.789474,36.842105,26.315789,15.789474,5.263158,0.000000,1.578947
Fluminense,31.578947,47.368421,15.789474,0.000000,0.000000,5.263158,1.052632
Fortaleza,31.578947,26.315789,26.315789,15.789474,0.000000,0.000000,1.263158
Goiás,31.578947,57.894737,10.526316,0.000000,0.000000,0.000000,0.789474
Grêmio,26.315789,42.105263,10.526316,10.526316,10.526316,0.000000,1.368421
Internacional,42.105263,42.105263,5.263158,10.526316,0.000000,0.000000,0.842105
Palmeiras,21.052632,47.368421,31.578947,0.000000,0.000000,0.000000,1.105263
Santos,42.105263,36.842105,15.789474,5.263158,0.000000,0.000000,0.842105
São Paulo,47.368421,26.315789,21.052632,5.263158,0.000000,0.000000,0.842105
Vasco,36.842105,42.105263,10.526316,5.263158,5.263158,0.000000,1.000000

## Distribuição Poisson

In [15]:
#aplicando formula em cada valor
for i in n:
    d[i] = dist_poisson(d['media de gols'], i)

#tirando as colunas que não mais preciso
d.drop(['total', 'soma ponderada'], 1, inplace=True)

#deixando em porcentagem para melhor visualização
d_per = d.copy()

for i in n:
    d_per[i] = d_per[i].apply(lambda x: x*100)
    
d_per

visitante placar,0,1,2,3,4,5,media de gols
visitante,,,,,,,
Athlético-Pr,26.826245,35.297691,23.222165,10.185160,3.350382,0.881679,1.315789
Atlético-Mg,40.871514,36.569249,16.359927,4.879277,1.091417,0.195306,0.894737
Avaí,65.635556,27.636023,5.818110,0.816577,0.085955,0.007238,0.421053
Bahia,34.901807,36.738744,19.336181,6.784625,1.785428,0.375880,1.052632
Botafogo-Rj,53.175153,33.584307,10.605571,2.232752,0.352540,0.044531,0.631579
Ceará,50.448835,34.517624,11.808661,2.693203,0.460680,0.063040,0.684211
Chapecoense,45.408372,35.848715,14.150809,3.723897,0.734980,0.116049,0.789474
Corinthians,40.871514,36.569249,16.359927,4.879277,1.091417,0.195306,0.894737
Cruzeiro,47.862297,35.266956,12.993089,3.191285,0.587868,0.086633,0.736842
Csa,69.182583,25.488320,4.695217,0.576606,0.053108,0.003913,0.368421
Flamengo,20.619203,32.556636,25.702607,13.527688,5.339877,1.686277,1.578947
Fluminense,34.901807,36.738744,19.336181,6.784625,1.785428,0.375880,1.052632
Fortaleza,28.275969,35.717013,22.558114,9.498153,2.999417,0.757747,1.263158
Goiás,45.408372,35.848715,14.150809,3.723897,0.734980,0.116049,0.789474
Grêmio,25.450850,34.827479,23.829328,10.869518,3.718519,1.017700,1.368421
Internacional,43.080262,36.278115,15.274996,4.287718,0.902677,0.152030,0.842105
Palmeiras,33.112373,36.597886,20.225148,7.451370,2.058931,0.455132,1.105263
Santos,43.080262,36.278115,15.274996,4.287718,0.902677,0.152030,0.842105
São Paulo,43.080262,36.278115,15.274996,4.287718,0.902677,0.152030,0.842105
Vasco,36.787944,36.787944,18.393972,6.131324,1.532831,0.306566,1.000000

## Previsão Under:

In [16]:
print('times possiveis (MANDANTE):')
display(test['mandante'].unique())

print('times possiveis (VISITANTE):')
display(test['visitante'].unique())

times possiveis (MANDANTE):

array(['Atlético-Mg', 'Chapecoense', 'Flamengo', 'São Paulo',
       'Athlético-Pr', 'Bahia', 'Ceará', 'Fluminense', 'Palmeiras',
       'Grêmio', 'Avaí', 'Csa', 'Vasco', 'Corinthians', 'Cruzeiro',
       'Fortaleza', 'Internacional', 'Goiás', 'Botafogo-Rj', 'Santos'],
      dtype=object)

times possiveis (VISITANTE):

array(['Avaí', 'Internacional', 'Cruzeiro', 'Botafogo-Rj', 'Vasco',
       'Corinthians', 'Csa', 'Goiás', 'Fortaleza', 'Santos', 'Grêmio',
       'Palmeiras', 'Atlético-Mg', 'Chapecoense', 'Ceará', 'Athlético-Pr',
       'Flamengo', 'São Paulo', 'Bahia', 'Fluminense'], dtype=object)

In [17]:
#time_mandante = input(print('digite um time dos mandantes:'))
#time_visitante = input(print('digite um time dos visitantes:'))

#time mandante
#m = b.loc[time_mandante]
m = b.loc['Flamengo']

#time visitante
#v = d.loc[time_visitante]
v = d.loc['Palmeiras']

tabela = pd.DataFrame({'mandante': m, 'visitante': v})
tabela.fillna(0, inplace = True) #colocando 0 nos valores N.A
tabela

               mandante  visitante
0              0.052478   0.331124
1              0.154671   0.365979
2              0.227936   0.202251
3              0.223937   0.074514
4              0.165006   0.020589
5              0.097267   0.004551
6              0.047780   0.000000
media de gols  2.947368   1.105263

# PROBABILIDADE

## UNDER 0,5

In [18]:
lista = [['0x0', m.loc[0], v.loc[0], m.loc[0]*v.loc[0]]]
tabela = pd.DataFrame(lista, columns = ['Placar', 'Prob gol mandante', 'Prob gol visitante', 'Prob de Placar Exato'])

#Deixando tudo em porcentagem:
tabela['Prob gol mandante'] = tabela['Prob gol mandante'].apply(lambda x: x*100)
tabela['Prob gol visitante'] = tabela['Prob gol visitante'].apply(lambda x: x*100)
tabela['Prob de Placar Exato'] = tabela['Prob de Placar Exato'].apply(lambda x: x*100)

#total probabilidade under 0.5
under_05 = tabela['Prob de Placar Exato'].sum()
print('total probabilidade under 0.5 é de ->', under_05)
tabela

total probabilidade under 0.5 é de -> 1.737658655907762

  Placar  Prob gol mandante  Prob gol visitante  Prob de Placar Exato
0    0x0           5.247762           33.112373              1.737659

## UNDER 1,5

In [19]:
#PROBABILIDADE DE GOLS
lista = [['0x0', m.loc[0], v.loc[0], m.loc[0]*v.loc[0]], ['0x1', m.loc[0], v.loc[1], m.loc[0]*v.loc[1]], 
         ['1x1', m.loc[1], v.loc[1], m.loc[1]*v.loc[1]], ['1x0', m.loc[1], v.loc[0], m.loc[1]*v.loc[0]]]
tabela = pd.DataFrame(lista, columns = ['Placar', 'Prob gol mandante', 'Prob gol visitante', 'Prob de Placar Exato'])

#Deixando tudo em porcentagem:
tabela['Prob gol mandante'] = tabela['Prob gol mandante'].apply(lambda x: x*100)
tabela['Prob gol visitante'] = tabela['Prob gol visitante'].apply(lambda x: x*100)
tabela['Prob de Placar Exato'] = tabela['Prob de Placar Exato'].apply(lambda x: x*100)

#total probabilidade under 1.5
under_15 = tabela['Prob de Placar Exato'].sum()
print('total probabilidade under 1.5 é de ->', under_15)
tabela

total probabilidade under 1.5 é de -> 14.440376641892758

  Placar  Prob gol mandante  Prob gol visitante  Prob de Placar Exato
0    0x0           5.247762           33.112373              1.737659
1    0x1           5.247762           36.597886              1.920570
2    1x1          15.467089           36.597886              5.660628
3    1x0          15.467089           33.112373              5.121520

## UNDER 2,5

In [20]:
#PROBABILIDADE DE GOLS
lista = [['0x0', m.loc[0], v.loc[0], m.loc[0]*v.loc[0]], ['0x1', m.loc[0], v.loc[1], m.loc[0]*v.loc[1]], ['0x2', m.loc[0], v.loc[2], m.loc[0]*v.loc[2]], 
         ['1x1', m.loc[1], v.loc[1], m.loc[1]*v.loc[1]], ['1x0', m.loc[1], v.loc[0], m.loc[1]*v.loc[0]], ['2x0', m.loc[2], v.loc[0], m.loc[2]*v.loc[0]]]
tabela = pd.DataFrame(lista, columns = ['Placar', 'Prob gol mandante', 'Prob gol visitante', 'Prob de Placar Exato'])

#Deixando tudo em porcentagem:
tabela['Prob gol mandante'] = tabela['Prob gol mandante'].apply(lambda x: x*100)
tabela['Prob gol visitante'] = tabela['Prob gol visitante'].apply(lambda x: x*100)
tabela['Prob de Placar Exato'] = tabela['Prob de Placar Exato'].apply(lambda x: x*100)

#total probabilidade under 2.5
under_25 = tabela['Prob de Placar Exato'].sum()
print('total probabilidade under 2.5 é de ->', under_25)
tabela

total probabilidade under 2.5 é de -> 23.049247849901157

  Placar  Prob gol mandante  Prob gol visitante  Prob de Placar Exato
0    0x0           5.247762           33.112373              1.737659
1    0x1           5.247762           36.597886              1.920570
2    0x2           5.247762           20.225148              1.061368
3    1x1          15.467089           36.597886              5.660628
4    1x0          15.467089           33.112373              5.121520
5    2x0          22.793605           33.112373              7.547504

## OVER:

f = d.copy()

#----------PRÉ-PROCESSAMENTOS:----------

f.drop(['media de gols'], 1, inplace=True) 

#Somando probabilidades de mais de 3 gols, na coluna de 3 gols
for i in f.columns:
    if i > 3:
        f[3] += f[i]
        
f.drop([4, 5], 1, inplace=True) #excluido coluna ja que não é mais necessaria

## OVER 0.5

#PROBABILIDADE DE GOLS
lista = [['0x0', m.loc[0], v.loc[0], m.loc[0]*v.loc[0]], ['0x1', m.loc[0], v.loc[1], m.loc[0]*v.loc[1]], ['0x2', m.loc[0], v.loc[2], m.loc[0]*v.loc[2]], 
         ['1x1', m.loc[1], v.loc[1], m.loc[1]*v.loc[1]], ['1x0', m.loc[1], v.loc[0], m.loc[1]*v.loc[0]], ['2x0', m.loc[2], v.loc[0], m.loc[2]*v.loc[0]]]
tabela = pd.DataFrame(lista, columns = ['Placar', 'Prob gol mandante', 'Prob gol visitante', 'Prob de Placar Exato'])

#Deixando tudo em porcentagem:
tabela['Prob gol mandante'] = tabela['Prob gol mandante'].apply(lambda x: x*100)
tabela['Prob gol visitante'] = tabela['Prob gol visitante'].apply(lambda x: x*100)
tabela['Prob de Placar Exato'] = tabela['Prob de Placar Exato'].apply(lambda x: x*100)

#total probabilidade under 2.5
under_25 = tabela['Prob de Placar Exato'].sum()
print('total probabilidade under 2.5 é de ->', under_25)
tabela

## Comparando o time jogando como mandante e visitante:

In [22]:
#Tabela Poisson
tabela = pd.DataFrame({'mandante': b_per.loc[time_mandante], 'visitante': d_per.loc[time_mandante]})
tabela.fillna(0, inplace = True) #colocando 0 nos valores N.A
print('Comparação da probabilidade(POISSON) de gols do time:', time_mandante, '. Como mandante e visitante')
display(tabela)

#Tabela Distribuição de probabilidade
tabela = pd.DataFrame({'mandante': a_per.loc[time_mandante], 'visitante': c_per.loc[time_mandante]})
tabela.fillna(0, inplace = True) #colocando 0 nos valores N.A
print('Comparação da probabilidade de gols do time:', time_mandante, '. Como mandante e visitante')
display(tabela)

NameError: name 'time_mandante' is not defined

In [ ]:
tabela['mandante'].plot(figsize=(12,6), color="blue")
tabela['visitante'].plot(figsize=(12,6), color="red")

# USANDO RANKING ELO PARA PROBABILIDADES

calculo baseado no video: https://www.youtube.com/watch?v=9MVANEitWRM

# Probabilidade vitoria mandante

In [23]:
def prob_elo(elo_mandante, elo_visitante):
    prob = (elo_mandante/400)/((elo_mandante/400)+(elo_visitante/400)) #probabilidade de vitoria do time mandante
    return print('A probabilidade do time mandante ganhar do time visitante baseando-se no elo de ambos é de:', prob*100)

In [24]:
prob_elo(1971, 1886)

A probabilidade do time mandante ganhar do time visitante do baseando-se no elo de ambos é de: 51.10189266269122